//! Generates the cover-art lookup from the jpgs present in `assets/covers/`.
//!
//! `asset!()` is compile-time only — wasm can't probe the filesystem at runtime
//! — so "render the cover if its jpg exists" is resolved here: we emit one match
//! arm per file found, and the renderer treats a `Some` return as "art exists".
//! Drop a `<key>.jpg` into `assets/covers/` and rebuild; nothing else to wire.
//! See OREGONTRAIL_IMAGE_KEYS.md for the key convention.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let covers_dir = Path::new(&manifest).join("assets/covers");
    // Re-run when art is added or removed.
    println!("cargo:rerun-if-changed=assets/covers");

    let mut keys: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&covers_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("jpg") {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    keys.push(stem.to_string());
                }
            }
        }
    }
    keys.sort();

    let mut code = String::from(
        "// Generated by build.rs from assets/covers/*.jpg — do not edit.\n\
         pub(crate) fn cover_asset(key: &str) -> Option<Asset> {\n    match key {\n",
    );
    for k in &keys {
        // `{k:?}` emits the quoted string-literal pattern; the path uses the raw stem.
        code.push_str(&format!(
            "        {k:?} => Some(asset!(\"/assets/covers/{k}.jpg\")),\n"
        ));
    }
    code.push_str("        _ => None,\n    }\n}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("covers.rs"), code).expect("write covers.rs");
}
