[package]
name = "adventure"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
retro-kit = { workspace = true }
parser-kit = { workspace = true }

dioxus = { workspace = true }
serde = { workspace = true }
gloo-timers = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]
